version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ValueX-Telegram-Bot"
s3_prefix = "ValueX-Telegram-Bot"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
resolve_s3 = true
