AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ValueX-Telegram-Bot

Globals:
  Function:
    Timeout: 3
    Runtime: python3.10
    Architectures:
      - arm64

Resources:
  PTBFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ptb/
      Handler: start.lambda_handler
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  TelegramApi:
    Description: "Lambda Function URL for PTB API"
    Value:
      Fn::GetAtt: PTBFunctionUrl.FunctionUrl
